// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9QiIs0yO-cspAZqq-rPMOnb53Bdnegv0',
    appId: '1:107383548493:android:675dd07f0b0dccfcba4a04',
    messagingSenderId: '107383548493',
    projectId: 'cinaddict-24cd8',
    storageBucket: 'cinaddict-24cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYf8Dq2QUOzAaPn-iPcrCnq1JY7Pktmg',
    appId: '1:107383548493:ios:06d254f19b1276b7ba4a04',
    messagingSenderId: '107383548493',
    projectId: 'cinaddict-24cd8',
    storageBucket: 'cinaddict-24cd8.appspot.com',
    androidClientId: '107383548493-fvo83iuqf2q3spdtqj0s7ktg1pv8q5fp.apps.googleusercontent.com',
    iosClientId: '107383548493-vf4m1d2qeorbd6aje8r2fme7mv3f0ps1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinaddict',
  );
}
