name: Build APK
on: push
jobs:
  hosting:
    name: Build Cinaddict
    runs-on: ubuntu-latest
    steps:
      #Checkout Repository
      - uses: actions/checkout@v2
      
      #Install Flutter Command
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      #Build Flutter App
      - name: Build Cinaddict
        run: |
          flutter pub get
          flutter build apk
